spring.profiles.include: 
   - api

server:
   port: 8080

spring.http.encoding: 
  charset: UTF-8
  enabled: true
  force: true

spring:
  mustache:
    suffix: .html
viewname:
  chatroom:
    enter: /chat/room-enter
    detail: /chat/room-detail
